version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    commit-message:
      # prevent netlify build
      prefix: '[skip ci]'
    open-pull-requests-limit: 99
    versioning-strategy: increase-if-necessary
