CREATE TABLE ITEMS_NEW
(
 ITEM_ID	VARCHAR2(50),
 ITEM_NAME	VARCHAR2(50)
);
INSERT INTO ITEMS_NEW VALUES('001','ITEM 1'); 
INSERT INTO ITEMS_NEW VALUES('002','ITEM 2');
INSERT INTO ITEMS_NEW VALUES('003','ITEM 3');
INSERT INTO ITEMS_NEW VALUES('004','ITEM 4');
INSERT INTO ITEMS_NEW VALUES('005','ITEM 5');
INSERT INTO ITEMS_NEW VALUES('006','ITEM 6');
COMMIT;
