name: Auto Merge Dependency Updates

on:
  - pull_request

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: tjenkinson/gh-action-auto-merge-dependency-updates@1ff3f19
        with:
          allowed-actors: dependabot[bot]
