name: Auto Merge Dependency Updates

on:
  - pull_request_target

permissions:
  contents: read
  pull-requests: write

jobs:
  run:
    runs-on: ubuntu-latest
    concurrency:
      group: 'automerge:run:${{ github.head_ref }}'
      cancel-in-progress: true
    steps:
      - uses: tjenkinson/gh-action-auto-merge-dependency-updates@964cf1547be62862846b42466ae1f68f7bdafee8 # v1.4.2
        with:
          repo-token: ${{ secrets.CI_GITHUB_TOKEN }}
          use-auto-merge: true
          allowed-actors: renovate[bot]
