name: Auto Merge Dependency Updates

on:
  - pull_request_target

permissions:
  contents: read
  pull-requests: write

jobs:
  run:
    runs-on: ubuntu-latest
    concurrency:
      group: '${{ github.workflow }}:${{ github.job }}:${{ github.ref }}'
      cancel-in-progress: true
    steps:
      - uses: tjenkinson/gh-action-auto-merge-dependency-updates@c75e7647e59e2569ff9f4b85107cd181d26e449b # v1
        with:
          repo-token: ${{ secrets.CI_GITHUB_TOKEN }}
          allowed-actors: renovate[bot]
